apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi
  labels:
    app: weatherapi
    kubernetes.azure.com/generator: devhub
  namespace: weatherapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
        - name: weatherapi
          image: msazuredev.azurecr.io/weatherapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
